print('My name is "Siraj"')
print('''I live in Pakistan''')
print("I'm learning 'python' for Data Science")
print("Top VS code extensions for python for data science: ")
print("""1. Python Extension for Visual Studio Code""")
print("2. Jupyter")
print("3. Python Docstring Generator")
print("4. Pylance")
print('5. Better Comments')
print("6. Jupyter Keymap")